# Generated by Django 5.0.1 on 2024-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('doi', models.CharField(max_length=50)),
                ('pmid', models.SlugField(max_length=8, unique=True)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('author_info', models.TextField()),
                ('abstract', models.TextField()),
                ('background', models.TextField()),
                ('objective', models.TextField()),
                ('method', models.TextField()),
                ('results', models.TextField()),
                ('conclusions', models.TextField()),
            ],
        ),
    ]
