# Generated by Django 5.0.1 on 2024-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='label',
            field=models.CharField(choices=[('rct', 'RCT'), ('meta', 'Meta-Analysis'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='conclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
