# Generated by Django 5.0.1 on 2024-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_abstract_label_alter_abstract_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='label',
            field=models.CharField(choices=[('RCT', 'RCT'), ('Meta-Analysis', 'Meta-Analysis'), ('Unknown', 'Unknown')], default='Unknown', max_length=15),
        ),
    ]
